//
//  SettingsShowRouter.swift
//  Geofencing
//
//  Created by msm72 on 12/28/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
@objc protocol SettingsShowRoutingLogic {
//    func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SettingsShowDataPassing {
    var dataStore: SettingsShowDataStore? { get }
}

class SettingsShowRouter: NSObject, SettingsShowRoutingLogic, SettingsShowDataPassing {
    // MARK: - Properties
    weak var viewController: SettingsShowViewController?
    var dataStore: SettingsShowDataStore?
    
    
    // MARK: - Class Initialization
    deinit {
        print("SettingsShowRouter: deinit...")
    }
    

    // MARK: - Routing
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
    
    
    // MARK: - Navigation
//    func navigateToSomewhere(source: SettingsShowViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
    
    
    // MARK: - Passing data
//    func passDataToSomewhere(source: SettingsShowDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
