//
//  SettingsShowPresenter.swift
//  Geofencing
//
//  Created by msm72 on 12/28/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol SettingsShowPresentationLogic {
    func presentSomething(fromResponseModel responseModel: SettingsShowModels.Something.ResponseModel)
}

class SettingsShowPresenter: SettingsShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: SettingsShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        print("SettingsShowPresenter: deinit...")
    }
    

    // MARK: - Presentation Logic implementation
    func presentSomething(fromResponseModel responseModel: SettingsShowModels.Something.ResponseModel) {
        let viewModel = SettingsShowModels.Something.ViewModel()
        viewController?.displaySomething(fromViewModel: viewModel)
    }
}
