//
//  SettingsShowInteractor.swift
//  Geofencing
//
//  Created by msm72 on 12/28/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol SettingsShowBusinessLogic {
    func doSomething(withRequestModel requestModel: SettingsShowModels.Something.RequestModel)
}

protocol SettingsShowDataStore {
//     var name: String { get set }
}

class SettingsShowInteractor: SettingsShowBusinessLogic, SettingsShowDataStore {
    // MARK: - Properties
    var presenter: SettingsShowPresentationLogic?
    var worker: SettingsShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Class Initialization
    deinit {
        print("SettingsShowInteractor: deinit...")
    }
    

    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: SettingsShowModels.Something.RequestModel) {
        worker = SettingsShowWorker()
        worker?.doSomeWork()
        
        let responseModel = SettingsShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
