//
//  MainShowPresenter.swift
//  Geofencing
//
//  Created by msm72 on 12/28/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Presentation Logic protocols
protocol MainShowPresentationLogic {
    func presentSomething(fromResponseModel responseModel: MainShowModels.Something.ResponseModel)
}

class MainShowPresenter: MainShowPresentationLogic {
    // MARK: - Properties
    weak var viewController: MainShowDisplayLogic?
    
    
    // MARK: - Class Initialization
    deinit {
        print("MainShowPresenter: deinit...")
    }
    

    // MARK: - Presentation Logic implementation
    func presentSomething(fromResponseModel responseModel: MainShowModels.Something.ResponseModel) {
        let viewModel = MainShowModels.Something.ViewModel()
        viewController?.displaySomething(fromViewModel: viewModel)
    }
}
