//
//  MainShowInteractor.swift
//  Geofencing
//
//  Created by msm72 on 12/28/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Business Logic protocols
protocol MainShowBusinessLogic {
    func doSomething(withRequestModel requestModel: MainShowModels.Something.RequestModel)
}

protocol MainShowDataStore {
//     var name: String { get set }
}

class MainShowInteractor: MainShowBusinessLogic, MainShowDataStore {
    // MARK: - Properties
    var presenter: MainShowPresentationLogic?
    var worker: MainShowWorker?
    
    // ... protocol implementation
//    var name: String = ""
    
    
    // MARK: - Class Initialization
    deinit {
        print("MainShowInteractor: deinit...")
    }
    

    // MARK: - Business logic implementation
    func doSomething(withRequestModel requestModel: MainShowModels.Something.RequestModel) {
        worker = MainShowWorker()
        worker?.doSomeWork()
        
        let responseModel = MainShowModels.Something.ResponseModel()
        presenter?.presentSomething(fromResponseModel: responseModel)
    }
}
