//
//  MainShowWorker.swift
//  Geofencing
//
//  Created by msm72 on 12/28/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainShowWorker {
    // MARK: - Class Initialization
    deinit {
        print("MainShowWorker: deinit...")
    }
    

    // MARK: - Business Logic
    func doSomeWork() {
    }
}
