//
//  MainShowModel.swift
//  Geofencing
//
//  Created by msm72 on 12/28/18.
//  Copyright (c) 2018 golos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit
import CoreLocation

// MARK: - Data models
struct MainShowModel {
    // MARK: - Properties
    var settingsRadiusIndex: Int = 0
    var settingsRadiusValue: Float = UserDefaults.standard.float(forKey: settingsRadiusKey)
    
    var settingsUserCurrentLocation: CLLocation?
    var settingsGeofence: CLLocationCoordinate2D?

    var settingsWiFiIndex: Int = 0
    var settingsWiFiValue: String = UserDefaults.standard.string(forKey: settingsWiFiKey) ?? "XXX"    
    
    var settingsPointAnnotation: MKPointAnnotation?
    
    
    // MARK: - Structure Functions
    mutating func clearAllProperties() {
        UserDefaults.standard.dictionaryRepresentation().keys.forEach { key in
            UserDefaults.standard.removeObject(forKey: key)
        }
        
        self.settingsWiFiIndex = 0
        self.settingsWiFiValue = "XXX"
        
        self.settingsRadiusIndex = 0
        self.settingsRadiusValue = 0.0
    }
}
